#pragma once

// Mouse buttons
#define GAMENG_MOUSE_BUTTON_1         0
#define GAMENG_MOUSE_BUTTON_2         1
#define GAMENG_MOUSE_BUTTON_3         2
#define GAMENG_MOUSE_BUTTON_4         3
#define GAMENG_MOUSE_BUTTON_5         4
#define GAMENG_MOUSE_BUTTON_6         5
#define GAMENG_MOUSE_BUTTON_7         6
#define GAMENG_MOUSE_BUTTON_8         7
#define GAMENG_MOUSE_BUTTON_LAST      GAMENG_MOUSE_BUTTON_8
#define GAMENG_MOUSE_BUTTON_LEFT      GAMENG_MOUSE_BUTTON_1
#define GAMENG_MOUSE_BUTTON_RIGHT     GAMENG_MOUSE_BUTTON_2
#define GAMENG_MOUSE_BUTTON_MIDDLE    GAMENG_MOUSE_BUTTON_3
